name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          make test
  Test_Square:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configuration et exécution du test de la fonction square
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest -R square --verbose --output-on-failure --square_values "5;10;15"
  Deployment:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Déploiement sur serveur
        run: echo "deploy"
