name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Compilation
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
  Test_Addition:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configuration et exécution du test d'addition
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest -R t1

  Test_Subtraction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configuration et exécution du test de soustraction
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest -R t2

  Test_Multiplication:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configuration et exécution du test de multiplication
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest -R t3

  Test_Division:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configuration et exécution du test de division
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest -R t4

  Test_Square:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configuration et exécution du test de la fonction square
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest -R t5
  Deployment:
    runs-on: ubuntu-latest
    needs: [Test_Addition, Test_Subtraction, Test_Multiplication, Test_Division, Test_Square]
    steps:
      - name: Déploiement sur serveur
        run: echo "deploy"
